### PR TITLE
Fix Regigigas hunt

### PR DESCRIPTION
**Pull request by David34920**
Regigigas has 2 dialog phases which implies we get stuck waiting for the white screen in phase ENTER_STATIC_COMBAT_3.

To fix that, the A button is pressed during the phase ENTER_STATIC_COMBAT_3.
Also, the delay for Regigigas needs to be set to 5.5.

In this MR the delay comments also include the value to hunt Uxie (3s).

### CODE REVIEW

**Comment by David34920** [comment]
Here the result
https://github.com/user-attachments/assets/69dfd238-e990-48b9-acc2-484f1bf2a675

**Comment by Gr33nBug** [comment]
Hi, David. 
Just for clarification as I haven't tried to catch Regigigas yet: Is it possible to save the game between those two dialogue phases so after softresetting you only need to do the second one?

**Comment by David34920** [comment]
The two dialog phases are after the fight launch, so you save in front of him as always.
You also need the 3 other regis in your team.

**Comment by Dinones** [comment]
> The two dialog phases are after the fight launch, so you save in front of him as always.

I think @Gr33nBug means if you can have the first dialog and then save before the second one, or if the second one goes straight after the first one.

**Comment by David34920** [comment]
The second dialog box is at the second 5 of the video.
You can't save at this point.

Note: A delay of 5.5 gives some false positives, I'm currently trying 6.5

**Comment by Dinones** [comment]
Okay, thank you for the clarification! Let me know when it's working, and I'll accept the PR.

On the other hand, do you have any idea of how we could make it work without having to change the delay?

**Comment by David34920** [comment]
I think we can remove the delay and some steps if we detect more precisely the encounter dialog box (second 20).
In that case, the workflow could be:

1. Start game
2. Press A until that box appears the first time
3. Wait until the box disappears
4. Check shiny

"Less is more"

To detect the box, we can also check the border color, not only the white content.

**Comment by Dinones** [comment]
The workflow makes sense. The problem is that detecting the white text box would also detect the white flashing and load screen. But I like what you said here:

> To detect the box, we can also check the border color, not only the white content.

**Comment by David34920** [comment]
The correct value was 7 the PR is updated with that value.
And I found it, I can confirm that the Telegram integration works well, thanks a lot :)

IMG_5332

**Comment by Dinones** [comment]
Ohhh congratulations!! Thank you for confirming! Then, is the PR ready to be accepted?

**Pull request merged**
