### PR TITLE
Shiny Hunter for Shaymin

### PR DESCRIPTION
**Pull request by Gr33nBug**
A new shiny hunter choice done specifically for the static Shaymin event on Brilliant Diamond/Shiny Pearl. This new one is about 33% faster than the regular static shiny hunter. It replicates in broad terms this [video (YouTube link)](https://youtu.be/gG1AOOxC6UY?si=OrfooZcim4G8nNhC): 

I have done over 1000 tries using this one and it seems to work flawlessly. Tested on the virtual machine recommended on the tutorial and on real hardware. 

Still trying for the shiny though... No false positives so far.

### CODE REVIEW

**Comment by David34920** [comment]
Great, if you equip the bike, can it be even faster?

**Comment by Gr33nBug** [comment]
> Great, if you equip the bike, can it be even faster?

It can be faster maybe. I tested pressing the start/plus button and it didn't work at the time so I just focused on making it work by running. Also I wanted to have some margin of error to make sure the zone is reloaded but the times running down and up could be shortened by 0.5-1.0 seconds.

**Comment by David34920** [comment]
I was thinking that we start the app with the player already in the bike.

The odds are 4096 so it's around 68 minutes if we count that we save 1s per try.

I don't know if it worth doing it.

**Comment by Gr33nBug** [comment]
> I was thinking that we start the app with the player already in the bike.

When the player interacts with shaymin, unfortunately the game makes them get off their bike. So after each battle we have to make the player get on the bike again then losing that second. I'm going to test some things and I'll report my progress later.

**Pull request closed without merging**
